// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMNafKZfoboTq2L53OCSp9Sk_Yd6cz-rg',
    appId: '1:198799213199:android:e2762d09dcd7df9512a6fa',
    messagingSenderId: '198799213199',
    projectId: 'recipeapp-6355d',
    storageBucket: 'recipeapp-6355d.appspot.com',
  );

  static  FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCbuK0JwU0qotXTl8NbFjmaSviescNBeCM',
    appId: '1:198799213199:ios:ca158a6adef9cccb12a6fa',
    messagingSenderId: '198799213199',
    projectId: 'recipeapp-6355d',
    storageBucket: 'recipeapp-6355d.appspot.com',
    androidClientId: '198799213199-mhqadieaklm3vnetl1mcqgtikg9rpadh.apps.googleusercontent.com',
    iosClientId: '198799213199-e94k1jvqencib1sh3vinui918jkg6e0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitbasix',
  );
}
